sudo: false

language: go

os:
 - linux

go:
- 1.9.2
- tip

script:
  - echo $TRAVIS_GO_VERSION
  - go get -v github.com/Masterminds/glide
  - glide install
  - cd dnscrypt-proxy

  - go clean
  - env GOOS=plan9 go build

  - go clean
  - env GOOS=solaris go build

  - go clean
  - env GOOS=windows GOARCH=386 go build
  - mkdir win32
  - ln dnscrypt-proxy.exe win32/
  - ln dnscrypt-proxy.toml win32/
  - zip -9 -r dnscrypt-proxy-win32-${TRAVIS_TAG:-dev}.zip win32

  - go clean
  - env GOOS=windows GOARCH=amd64 go build
  - mkdir win64
  - ln dnscrypt-proxy.exe win64/
  - ln dnscrypt-proxy.toml win64/
  - zip -9 -r dnscrypt-proxy-win64-${TRAVIS_TAG:-dev}.zip win64

  - go clean
  - env GOOS=openbsd GOARCH=386 go build
  - mkdir openbsd-i386
  - ln dnscrypt-proxy openbsd-i386/
  - ln dnscrypt-proxy.toml openbsd-i386/
  - tar czpvf dnscrypt-proxy-openbsd_i386-${TRAVIS_TAG:-dev}.tar.gz openbsd-i386

  - go clean
  - env GOOS=openbsd GOARCH=amd64 go build
  - mkdir openbsd-amd64
  - ln dnscrypt-proxy openbsd-amd64/
  - ln dnscrypt-proxy.toml openbsd-amd64/
  - tar czpvf dnscrypt-proxy-openbsd_amd64-${TRAVIS_TAG:-dev}.tar.gz openbsd-amd64

  - go clean
  - env GOOS=freebsd GOARCH=386 go build
  - mkdir freebsd-i386
  - ln dnscrypt-proxy freebsd-i386/
  - ln dnscrypt-proxy.toml freebsd-i386/
  - tar czpvf dnscrypt-proxy-freebsd_i386-${TRAVIS_TAG:-dev}.tar.gz freebsd-i386

  - go clean
  - env GOOS=freebsd GOARCH=amd64 go build
  - mkdir freebsd-amd64
  - ln dnscrypt-proxy freebsd-amd64/
  - ln dnscrypt-proxy.toml freebsd-amd64/
  - tar czpvf dnscrypt-proxy-freebsd_amd64-${TRAVIS_TAG:-dev}.tar.gz freebsd-amd64

  - go clean
  - env GOOS=dragonfly GOARCH=amd64 go build
  - mkdir dragonflybsd-amd64
  - ln dnscrypt-proxy dragonflybsd-amd64/
  - ln dnscrypt-proxy.toml dragonflybsd-amd64/
  - tar czpvf dnscrypt-proxy-dragonflybsd_amd64-${TRAVIS_TAG:-dev}.tar.gz dragonflybsd-amd64

  - go clean
  - env GOOS=netbsd GOARCH=386 go build
  - mkdir netbsd-i386
  - ln dnscrypt-proxy netbsd-i386/
  - ln dnscrypt-proxy.toml netbsd-i386/
  - tar czpvf dnscrypt-proxy-netbsd_i386-${TRAVIS_TAG:-dev}.tar.gz netbsd-i386

  - go clean
  - env GOOS=netbsd GOARCH=amd64 go build
  - mkdir netbsd-amd64
  - ln dnscrypt-proxy netbsd-amd64/
  - ln dnscrypt-proxy.toml netbsd-amd64/
  - tar czpvf dnscrypt-proxy-netbsd_amd64-${TRAVIS_TAG:-dev}.tar.gz netbsd-amd64

  - go clean
  - env GOOS=linux GOARCH=386 go build
  - mkdir linux-i386
  - ln dnscrypt-proxy linux-i386/
  - ln dnscrypt-proxy.toml linux-i386/  
  - tar czpvf dnscrypt-proxy-linux_i386-${TRAVIS_TAG:-dev}.tar.gz linux-i386

  - go clean
  - env GOOS=linux GOARCH=amd64 go build
  - mkdir linux-x86_64
  - ln dnscrypt-proxy linux-x86_64/
  - ln dnscrypt-proxy.toml linux-x86_64/  
  - tar czpvf dnscrypt-proxy-linux_x86_64-${TRAVIS_TAG:-dev}.tar.gz linux-x86_64

  - go clean
  - env GOOS=linux GOARCH=arm go build
  - mkdir linux-arm
  - ln dnscrypt-proxy linux-arm/
  - ln dnscrypt-proxy.toml linux-arm/
  - tar czpvf dnscrypt-proxy-linux_arm-${TRAVIS_TAG:-dev}.tar.gz linux-arm

  - go clean
  - env GOOS=darwin GOARCH=amd64 go build
  - mkdir macos
  - ln dnscrypt-proxy macos/
  - ln dnscrypt-proxy.toml macos/  
  - tar czpvf dnscrypt-proxy-macos-${TRAVIS_TAG:-dev}.tar.gz macos

  - ls -l dnscrypt-proxy-*.tar.gz dnscrypt-proxy-*.zip

deploy:
  provider: releases
  api_key:
    secure: jtXaCwUY+LlovLJQgT+V2lDYvW/dHRWHZGiZLReJP19GA1x0aAFTzRBeESbvJ92lYu5HGOL6nmFUKn8Fl+HQ8kocK2bTE16AnvBxtLIgmOElHA2W+dIiJnIl7EfG9kNxzV75eGcH/YN+Skqwq95XmTsn9TvFhIPTcY1WuoV239fqS+rcDg3zdr0uM/kcYbyO7OFkvKU4ewTx5QoDJVgLDQo2fnPtGVsPr0M8XSFpTlfpmpJzEOS30aEOE18qKZaz/suNDO4Zgya7O374xQbY6WTiChpUMTTwQRuiExj3/8soSRPWXazZrHdkX+2My6gaZEslVRdCa4CUP6tPJoIX4b5Dmi3+WkYRkeUNNqpP+m26nV9PapQqg7S5K5lXjfaCkGGZLg/wLhtjeuGdk6H1+bbyPprxdXhplBV7yzDyjNWcbFFruOcvsuks9zBYIelR9dlFiIb33gq/zsams7usZNERvisR3bBLecH9qdxcimp/DB+tEN4i8aNGz+dYmHvWBAxNw+GjGiSs6wnZrJtqex1Q2j5ngSLDgMDiSHamd0m/yQjnN5jKklIIEgIhaS+jp50Qi3mMmnv03KvLbulmLkfh/vQ612F+gH/N+UbtDeva5SPGH4I/X01gJoHGGbXVmqlv2F1cwkFnWbY50kGIaHOLQFsWxUzjyBXPVXItRxQ=
  file:
    - dnscrypt-proxy-*.tar.gz
    - dnscrypt-proxy-*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: jedisct1/dnscrypt-proxy
    tags: true
    condition: "${TRAVIS_GO_VERSION} == 1.9.2"

after_deploy:
  - ls -l dnscrypt-proxy-*.tar.gz
