
####################################
#                                  #
#   dnscrypt-proxy configuration   #
#                                  #
####################################


############## Global settings ##############

## List of servers to use
## If this line is commented, all registered servers will be used

server_names = ["dnscrypt.org-fr", "adguard-dns"]


## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.

listen_addresses = ["127.0.0.1:53", "[::1]:53"]


## Whether to the server as a background process (linux only)
## Do not set to true if you are using systemd

daemonize = false


## Always use TCP to connect to upstream servers

force_tcp = false


## Timeout, in milliseconds

timeout = 2500


## Delay, in minutes, after which certificates are reloaded

cert_refresh_delay = 30


############## Filters ##############

## Immediately respond to IPv6-related queries with an empty response
## This makes things faster when there is no IPv6 connectivity

block_ipv6 = false


############## DNS Cache ##############

## Enable a basic DNS cache to reduce outgoing traffic

cache = true


## Cache size

cache_size = 256


## Minimum TTL for cached entries

cache_min_ttl = 600


## Maxmimum TTL for cached entries

cache_max_ttl = 86400


## TTL for negatively cached entries

cache_neg_ttl = 60


############## Servers ##############

## Remote lists of available servers
## Recommended: change the cache_file location to an absolute path

[sources]
  [sources."github-csv"]
  url = "https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v1/dnscrypt-resolvers.csv"
  minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
  cache_file = "dnscrypt-resolvers.csv"
  format = "v1"
  refresh_delay = 24


## Local, static list of available servers

[servers]
  [servers."dnscrypt.org-fr"]
  provider_name = "2.dnscrypt-cert.fr.dnscrypt.org"
  address = "212.47.228.136:443"
  public_key = "E801:B84E:A606:BFB0:BAC0:CE43:445B:B15E:BA64:B02F:A3C4:AA31:AE10:636A:0790:324D"

  [servers."dnscrypt.eu-nl"]
  provider_name = "2.dnscrypt-cert.resolver2.dnscrypt.eu"
  address = "77.66.84.233:443"
  public_key = "3748:5585:E3B9:D088:FD25:AD36:B037:01F5:520C:D648:9E9A:DD52:1457:4955:9F0A:9955"

  [servers."adguard-dns"]
  provider_name = "2.dnscrypt.default.ns1.adguard.com"
  address = "176.103.130.130:5443"
  public_key = "D12B:47F2:52DC:F2C2:BBF8:9910:86EA:F79C:E449:5D8B:16C8:A0C4:322E:52CA:3F39:0873"
